// Auto-generated Supabase types — regenerated by: bun run db:types
// Do not edit manually. Run the db:types script after any schema change.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
